### ISSUE TITLE
req.body is empty within V1 routes

### ISSUE THREAD

**Issue by Tehbb3** [xornet-cloud/Backend#7]
- bug report
### Demonstration of issue:
/src/routes/v1/v1.ts ~Ln139 :
```ts
  private generate_label_routes() {
    return express
      .Router()

...

      .post("/new", this.auth, (req: LoggedInRequest, res) => {

        // inserted code:
        console.log(req.body) // this just always returns an empty object??? {}

        this.db
          .new_label({ ...req.body, owner_uuid: req.user!.uuid })
          .then((label) => res.status(201).json(label))
          .catch((error) => res.status(400).json(error));
      });
```
As far as I can tell this is also an issue with updating banners and many other routes in v1.ts

Is there a piece of middleware somewhere that is clearing the body object?
or am I missing something here?

**Comment by Geoxor** [comment]
It works fine for me with this setup:

![image](https://user-images.githubusercontent.com/34042825/166192246-05b4fbcd-65b8-4b53-aa65-9fe6256bb573.png)
![image](https://user-images.githubusercontent.com/34042825/166192283-88618075-259d-45a0-a189-fe4e824126b7.png)
![image](https://user-images.githubusercontent.com/34042825/166192298-7341d8bd-0308-47f4-b868-2c3366720a5a.png)

**Comment by Geoxor** [comment]
make sure you're sending your auth token in the headers
![image](https://user-images.githubusercontent.com/34042825/166192494-3567852f-d331-4128-93b7-1999ac128c83.png)

**Comment by Tehbb3** [comment]
Got it working
![image](https://user-images.githubusercontent.com/62781302/166233017-1e366a0a-5b9f-4f8d-bf63-fffcacce1885.png)

I don't have access to my normal setup rn, and I didn't realise the 'content-type' headers aren't automatically set on the tool I was using ;-;

Thanks for the help though
Cheers
